package accounting.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import org.springframework.data.annotation.Id;

import java.util.Date;

/**
 * Database table mapping for the table which includes customers with their orders.
 */
@DynamoDBTable(tableName = "CustomerOrders")
public class CustomerOrder {

    @Id
    private CustomerOrderId customerOrderId;

    private String name;
    private String address;
    private Date orderDate;
    private String orderCurrency;
    private String orderReferenceNumber;
    private String productCode;
    private Integer productQuantity;
    private Integer productUnitPrice;

    public CustomerOrder() {
    }

    public void setCustomerData(String customerId, String name, String address) {
        setName(name);
        setAddress(address);
        this.customerOrderId = new CustomerOrderId(customerId, SortKeyUtils.createIdForCustomerData(customerId));
    }

    public void setOrderData(String customerId, Date orderDate, String orderCurrency, String orderReferenceNumber) {
        this.orderDate = orderDate;
        this.orderCurrency = orderCurrency;
        this.orderReferenceNumber = orderReferenceNumber;
        this.customerOrderId = new CustomerOrderId(customerId, SortKeyUtils.createIdForOrder(orderReferenceNumber));
    }

    public void setOrderItemData(String customerId, String orderReferenceNumber, String productCode, Integer productQuantity, Integer productUnitPrice) {
        this.orderReferenceNumber = orderReferenceNumber;
        this.productCode = productCode;
        this.productQuantity = productQuantity;
        this.productUnitPrice = productUnitPrice;
        this.customerOrderId = new CustomerOrderId(customerId, SortKeyUtils.createIdForOrderItem(orderReferenceNumber, productCode));
    }

    @DynamoDBHashKey(attributeName = "customerId")
    @DynamoDBAutoGeneratedKey()
    public String getCustomerId() {
        return customerOrderId != null ? customerOrderId.getCustomerId() : null;
    }

    public void setCustomerId(String customerId) {
        if (customerOrderId == null) {
            customerOrderId = new CustomerOrderId();
        }
        customerOrderId.setCustomerId(customerId);
    }

    @DynamoDBRangeKey(attributeName = "typeKey")
    public String getTypeKey() {
        return customerOrderId != null ? customerOrderId.getTypeKey() : null;
    }

    public void setTypeKey(String typeKey) {
        if (customerOrderId == null) {
            customerOrderId = new CustomerOrderId();
        }
        customerOrderId.setTypeKey(typeKey);
    }

    @DynamoDBAttribute
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBAttribute
    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @DynamoDBAttribute
    public Date getOrderDate() {
        return orderDate;
    }

    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    @DynamoDBAttribute
    public String getOrderCurrency() {
        return orderCurrency;
    }

    public void setOrderCurrency(String orderCurrency) {
        this.orderCurrency = orderCurrency;
    }

    @DynamoDBAttribute
    public String getOrderReferenceNumber() {
        return orderReferenceNumber;
    }

    public void setOrderReferenceNumber(String orderReferenceNumber) {
        this.orderReferenceNumber = orderReferenceNumber;
    }

    @DynamoDBAttribute
    public String getProductCode() {
        return productCode;
    }

    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    @DynamoDBAttribute
    public Integer getProductQuantity() {
        return productQuantity;
    }

    public void setProductQuantity(Integer productQuantity) {
        this.productQuantity = productQuantity;
    }

    @DynamoDBAttribute
    public Integer getProductUnitPrice() {
        return productUnitPrice;
    }

    public void setProductUnitPrice(Integer productUnitPrice) {
        this.productUnitPrice = productUnitPrice;
    }

    @Override
    public String toString() {
        return "CustomerOrder{" +
                "customerOrderId=" + customerOrderId +
                ", name='" + name + '\'' +
                ", address='" + address + '\'' +
                ", orderDate=" + orderDate +
                ", orderCurrency='" + orderCurrency + '\'' +
                ", orderReferenceNumber='" + orderReferenceNumber + '\'' +
                ", productCode='" + productCode + '\'' +
                ", productQuantity=" + productQuantity +
                ", productUnitPrice=" + productUnitPrice +
                '}';
    }
}
