package accounting.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.io.Serializable;

/**
 * Composite ID for {@link CustomerOrder} database table.
 * Includes customer ID and type of record - customer data, order data or order product data.
 */
public class CustomerOrderId implements Serializable {

    private static final long serialVersionUID = 1L;

    private String customerId;
    private String typeKey;

    public CustomerOrderId() {
    }

    public CustomerOrderId(String customerId, String typeKey) {
        this.customerId = customerId;
        this.typeKey = typeKey;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey()
    public String getCustomerId() {
        return customerId;
    }

    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    @DynamoDBRangeKey
    public String getTypeKey() {
        return typeKey;
    }

    public void setTypeKey(String typeKey) {
        this.typeKey = typeKey;
    }

    @Override
    public String toString() {
        return "CustomerOrderId{" +
                "customerId='" + customerId + '\'' +
                ", typeKey='" + typeKey + '\'' +
                '}';
    }
}
